name: Backend API CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install & Unit Tests
      run: |
        npm install
        npm run test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t nestapp .
    - name: Tags
      run: |
        docker tag nestapp ${{ secrets.DOCKER_USER }}/nestapp:${{ github.sha }}
        docker tag nestapp ${{ secrets.DOCKER_USER }}/nestapp:latest
    - name: push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/nestapp:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/nestapp:latest